mail_domain = 'company.com'
REDMINE_URL = 'https://prj.company.cog'
REDMINE_KEY = '9c68f1d5881b138_your_key_f76d4bb97e246'
ldap_server = 'ldaps://ldap.company.com:636/'
ldap_root_dn = 'cn=admin,dc=company,dc=com'
ldap_root_pw = "your_root_dn_password"
ldap_employees_dn = 'cn=people,ou=Company,dc=company,dc=com'
smtp_server = 'smtp.gmail.com'
smtp_port = 587
admin_mailbox = 'sysadmin@company.com'
admin_mailbox_pw = 'your_mail_password'